In [1]:
import torch

In [40]:
powers = torch.pow(torch.full((3, ), 2, dtype=torch.float32), torch.arange(1, 3+1))

In [41]:
powers.roll(0)

tensor([2., 4., 8.])

In [42]:
m = torch.stack([powers.roll(i) for i in range(3)], dim=1)

In [43]:
torch.tril(m)

tensor([[2., 0., 0.],
        [4., 2., 0.],
        [8., 4., 2.]])

In [21]:
torch.ones(1, 3) * torch.tril(m)

tensor([[2., 0., 0.],
        [4., 2., 0.],
        [8., 4., 2.]])

In [47]:
torch.ones(1, 3, dtype=torch.float32).mm(torch.tril(m)).squeeze()

tensor([14.,  6.,  2.])